// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhWwet6-DGoyGhYq0P9orlmK3L4Mjmj0',
    appId: '1:650251547522:web:fde8d56538804ed64b959b',
    messagingSenderId: '650251547522',
    projectId: 'makeplans-e3635',
    authDomain: 'makeplans-e3635.firebaseapp.com',
    storageBucket: 'makeplans-e3635.firebasestorage.app',
    measurementId: 'G-QHR6BRVLMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYg8Q3FWvBTlfrH4FzQ_kHYDspKAiCogw',
    appId: '1:650251547522:android:ece179a89e3a4d6f4b959b',
    messagingSenderId: '650251547522',
    projectId: 'makeplans-e3635',
    storageBucket: 'makeplans-e3635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikAZ7dhjTUoXoCpnEaBlpYwSGGGLwiGU',
    appId: '1:650251547522:ios:96b07ebe4cf666b64b959b',
    messagingSenderId: '650251547522',
    projectId: 'makeplans-e3635',
    storageBucket: 'makeplans-e3635.firebasestorage.app',
    iosBundleId: 'com.example.makeplans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikAZ7dhjTUoXoCpnEaBlpYwSGGGLwiGU',
    appId: '1:650251547522:ios:96b07ebe4cf666b64b959b',
    messagingSenderId: '650251547522',
    projectId: 'makeplans-e3635',
    storageBucket: 'makeplans-e3635.firebasestorage.app',
    iosBundleId: 'com.example.makeplans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEhWwet6-DGoyGhYq0P9orlmK3L4Mjmj0',
    appId: '1:650251547522:web:21ef7c4928f9f6a44b959b',
    messagingSenderId: '650251547522',
    projectId: 'makeplans-e3635',
    authDomain: 'makeplans-e3635.firebaseapp.com',
    storageBucket: 'makeplans-e3635.firebasestorage.app',
    measurementId: 'G-JJ6CRH0129',
  );
}
